<a href="https://colab.research.google.com/github/saokotie/Applied-Machine-Learning/blob/main/WorksheetPresentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np. random.random (10)
print(x)
y = np. random.random((3, 10))
print(y)
y = np.random.random((10, 3))
print(y)
y = np.random.random((3, 3, 3))
print(y)
y = np.random.random((10, 3))
print(y)
y.shape
y.dtype
type(y)
y.size


[0.60010678 0.75141428 0.00622013 0.04442933 0.40848348 0.55039522
 0.34110492 0.50986899 0.3332003  0.78217035]
[[0.4066583  0.91904094 0.94209656 0.11813116 0.86789799 0.14058854
  0.49212419 0.80198139 0.13946631 0.89124943]
 [0.02320022 0.51568609 0.10455097 0.56747165 0.67322078 0.34322551
  0.54595627 0.7151538  0.48680493 0.40406895]
 [0.77789839 0.49915811 0.78125146 0.54558999 0.80547476 0.81017378
  0.8553022  0.33712665 0.71452592 0.22390661]]
[[0.9207476  0.44316217 0.28729301]
 [0.55255389 0.57114981 0.61820217]
 [0.32473804 0.93710053 0.67972542]
 [0.14757118 0.60802779 0.84435319]
 [0.97024991 0.03870634 0.47961091]
 [0.69189696 0.21836393 0.16762159]
 [0.06328773 0.76812614 0.48981307]
 [0.12238475 0.75294008 0.42617197]
 [0.69862165 0.5448894  0.94081376]
 [0.89610477 0.30480402 0.77141801]]
[[[0.42965827 0.79082047 0.98101553]
  [0.59366441 0.92460217 0.59686941]
  [0.21996017 0.02635111 0.42467562]]

 [[0.62516761 0.70858395 0.19435042]
  [0.26461076 0.31064063 0.325

30

In [ ]:
import numpy as np
a = np.zeros(5)
b = np.ones(5)
c = np.ones(5) * 3
d = np.ones((3, 5))
e = np.array([[5,5,5,5,5], [1,1,1,1,1], [8,8,8,8,8]])
f = np.array([b * 5, b, b * 8])
h = np.ones(5, dtype=int)
y = np.random.random((10, 3))
print(y)         # wholee array
print(y[5, 2])  # element
print(y[5])     # row
print(y[5, :])  # row
print(y[:, 2])   # col
print(y[4:6, 1:3]) # 2d slice

[[0.50752165 0.63721591 0.30517622]
 [0.92859609 0.09012058 0.23299168]
 [0.1716267  0.35012848 0.87942187]
 [0.95451205 0.25969643 0.04319977]
 [0.59013455 0.47306906 0.05157321]
 [0.64817908 0.97704637 0.47861322]
 [0.42424841 0.13507467 0.14904776]
 [0.58149529 0.0233585  0.99173491]
 [0.91114398 0.42870054 0.50084937]
 [0.62809094 0.72416784 0.41008498]]
0.4786132156144375
[0.64817908 0.97704637 0.47861322]
[0.64817908 0.97704637 0.47861322]
[0.30517622 0.23299168 0.87942187 0.04319977 0.05157321 0.47861322
 0.14904776 0.99173491 0.50084937 0.41008498]
[[0.47306906 0.05157321]
 [0.97704637 0.47861322]]


In [ ]:
y = np.random.random((10, 3))
print(y)
z = y[4:6, 1:3]
print(z)
z[0, 0] = 0
print(z)
print(y)


[[0.4469689  0.31001842 0.09864351]
 [0.92049891 0.16963885 0.69093357]
 [0.69188749 0.23125166 0.78410711]
 [0.31509015 0.19136442 0.48389203]
 [0.63563311 0.2740077  0.231012  ]
 [0.35333796 0.98554104 0.61520355]
 [0.0801635  0.65611924 0.33659613]
 [0.93325967 0.71381438 0.75031048]
 [0.81088601 0.96037355 0.14594811]
 [0.48263121 0.97128275 0.58726216]]
[[0.2740077  0.231012  ]
 [0.98554104 0.61520355]]
[[0.         0.231012  ]
 [0.98554104 0.61520355]]
[[0.4469689  0.31001842 0.09864351]
 [0.92049891 0.16963885 0.69093357]
 [0.69188749 0.23125166 0.78410711]
 [0.31509015 0.19136442 0.48389203]
 [0.63563311 0.         0.231012  ]
 [0.35333796 0.98554104 0.61520355]
 [0.0801635  0.65611924 0.33659613]
 [0.93325967 0.71381438 0.75031048]
 [0.81088601 0.96037355 0.14594811]
 [0.48263121 0.97128275 0.58726216]]


In [ ]:
y = np.random.random ((10, 3))
print(y)
print(y[0])
print(y[0, :])
print(y[0:1, :])


[[0.37540363 0.96412527 0.66346513]
 [0.75499871 0.99757074 0.02070471]
 [0.4418079  0.96471098 0.49263591]
 [0.91934115 0.02802104 0.61420977]
 [0.31803189 0.24458902 0.16233535]
 [0.17980403 0.29401991 0.82153601]
 [0.55579662 0.17970155 0.91180272]
 [0.7853714  0.72592708 0.22607903]
 [0.71872291 0.98323709 0.88413943]
 [0.48391066 0.0828553  0.89617287]]
[0.37540363 0.96412527 0.66346513]
[0.37540363 0.96412527 0.66346513]
[[0.37540363 0.96412527 0.66346513]]


In [ ]:
# Scalar operation
# np.random.random will generate numbers between 0  and 1 (not including 1).

import numpy as np
x = np.random.random(10) * 100
print(x)
y = np.random.random((3, 10)) * 100
print(y)

[71.24275866 66.47737837 49.98311185 97.45621253 62.83731603 94.07791472
  2.89558443 63.16126675 64.98667943 80.70632958]
[[13.51230992 91.49339639 18.39935725 43.14618874 78.18083645 95.99929269
  27.29148936 35.56570178 88.76758045 39.07373181]
 [44.36724071 65.32571785  5.2012684  38.46783382  8.30891515 91.11096869
  68.90208958 44.95804889 43.63999232 74.31557291]
 [33.26135145  7.91128959 44.2076504  70.86977599 86.0542219  36.97736851
  50.53092788 31.32728309 99.54454191 15.94738295]]


In [ ]:
x = np.random.random((3, 5)) * 10 + 5
print(x)
y = np.random.random((3, 5)) + 5 * 10
print(y)

[[ 5.19876912  5.58876235  5.80991292  9.91426379 13.96918024]
 [11.86654181 11.94868015  7.22878445 14.76154606 11.74602061]
 [ 6.43987911 11.38485161 10.98801156  7.17112166  9.99124345]]
[[50.25638259 50.7113973  50.59275636 50.32455639 50.51755313]
 [50.39735814 50.22561844 50.07308103 50.83370064 50.03192365]
 [50.07227944 50.00938175 50.60177868 50.40131857 50.92863007]]


In [ ]:
temps = np.array([15, 18, 23, 20])
f_temps = temps * 9/5 + 32
print(f_temps)

[59.  64.4 73.4 68. ]


In [ ]:
# Boolean indexing of arrays
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x < 5)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
x[x > 5]
x[x % 2 == 0]
x[x ** 2 < 50]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[x > 5] = 5
print(x)

[[1 2 3]
 [4 5 5]
 [5 5 5]]


In [ ]:
x = np.array([[2,2], [4,4], [3, 5]])
y = np.array([[10, 20], [30, 40,], [50, 60]])
print(x < 4)
print(y[x < 4])

[[ True  True]
 [False False]
 [ True False]]
[10 20 50]


In [ ]:
x = np.random.random((10, 5))
np.sum(x, 0)
np.sum(x, 1)
np.sum(x)

np.float64(29.357804916806053)

In [ ]:
import numpy as np
import matplotlib. pyplot as plt
a = np. fromfile(" megt90n000cb. img", dtype= ' >i2 ' )

